services:
  - type: web
    name: ai-notes-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
